### PR TITLE
Fix #16 - Build Notifications Dropdown

### LINKED ISSUE #16: TODO: Build Notifications Dropdown
**Task**
Create an HTML/CSS segment that matches the **notifications dropdown** wireframe.

**Source Image:**
/design_notes/wireframes/notifications_dropdown.png

**File Destination**
/templates/elements/notifications_dropdown.html

### PR DESCRIPTION
**Pull request by tomekp97**
Hi! Wasn't sure how you compile your SCSS so to avoid potentially messing up the existing compiled CSS with a different compiler I stuck the CSS for the dropdown in the corresponding HTML file. Hope that's ok!

### CODE REVIEW

**Comment by BanjoFox** [comment]
Hey no worries :)

Right now I do not have an SCSS file for this although we do need one.  Currently all of the styles are either from Bulma, or /web/css/base.css, and /web/css/scratchpad.css

**Comment by BanjoFox** [comment]
That said... 
-everything- in /web/_sass/ is actually the from the project website [https://aardwolf.social](https://aardwolf.social)

**Comment by tomekp97** [comment]
I'll happily help out whenever I can! :+1: 

Just to clarify, do you mean that the files in **/web/_sass/** are to do with https://aardwolf.social and have no impact on any templates in this repository?

And just one last bit, by starting from scratch do you mean setting up SCSS to CSS compilation in this project so that it does affect the templates in this repository?  :)

If so I'm thinking of deleting the current SCSS files, copying the compiled CSS as it stands and splitting it up between new SCSS files and folder structure. Is this what you had in mind?

**Comment by BanjoFox** [comment]
Thanks!  I appreciate the help.
Right now I am still trying to figure out proper documentation but here we are :)

Here are the end goals regarding styles:
- Create a SASS structure to manage all of the layouts for the application
- Also create SASS for "themes" so that admins/users can customize the color scheme

**Pull request merged**
